openapi: 3.2.0
info:
  title: Docker Engine Service API
  version: '1.33'
  x-logo:
    url: https://docs.docker.com/images/logo-docker-main.png
  description: 'The Engine API is an HTTP API served by Docker Engine. It is the API the Docker client uses to communicate with the Engine, so everything the Docker client can do can be done with the API.


    Most of the client''s commands map directly to API endpoints (e.g. `docker ps` is `GET /containers/json`). The notable exception is running containers, which consists of several API calls.


    # Errors


    The API uses standard HTTP status codes to indicate the success or failure of the API call. The body of the response will be JSON in the following format:


    ```

    {

    "message": "page not found"

    }

    ```


    # Versioning


    The API is usually changed in each release of Docker, so API calls are versioned to ensure that clients don''t break.


    For Docker Engine 17.09, the API version is 1.32. To lock to this version, you prefix the URL with `/v1.32`. For example, calling `/info` is the same as calling `/v1.32/info`.


    Engine releases in the near future should support this version of the API, so your client will continue to work even if it is talking to a newer Engine.


    In previous versions of Docker, it was possible to access the API without providing a version. This behaviour is now deprecated will be removed in a future version of Docker.


    The API uses an open schema model, which means server may add extra properties to responses. Likewise, the server will ignore any extra query parameters and request body properties. When you write clients, you need to ignore additional properties in responses to ensure they do not break when talking to newer Docker daemons.


    This documentation is for version 1.33 of the API. Use this table to find documentation for previous versions of the API:


    Docker version | API version | Changes

    ----------------|-------------|---------

    17.09.x | 1.31 | API changes

    17.07.x | 1.31 | API changes

    17.06.x | 1.30 | API changes

    17.05.x | 1.29 | API changes

    17.04.x | 1.28 | API changes

    17.03.1 | 1.27 | API changes

    1.13.1 & 17.03.0 | 1.26 | API changes

    1.13.0 | 1.25 | API changes

    1.12.x | 1.24 | API changes

    1.11.x | 1.23 | API changes

    1.10.x | 1.22 | API changes

    1.9.x | 1.21 | API changes

    1.8.x | 1.20 | API changes

    1.7.x | 1.19 | API changes

    1.6.x | 1.18 | API changes


    # Authentication


    Authentication for registries is handled client side. The client has to send authentication details to various endpoints that need to communicate with registries, such as `POST /images/(name)/push`. These are sent as `X-Registry-Auth` header as a Base64 encoded (JSON) string with the following structure:


    ```

    {

    "username": "string",

    "password": "string",

    "email": "string",

    "serveraddress": "string"

    }

    ```


    The `serveraddress` is a domain/IP without a protocol. Throughout this structure, double quotes are required.


    If you have already got an identity token from the `/auth` endpoint, you can just pass this instead of credentials:


    ```

    {

    "identitytoken": "9cbaf023786cd7..."

    }

    ```'
servers:
- url: /v1.33
tags:
- name: Service
  x-displayName: Services
  description: Services are the definitions of tasks to run on a swarm. Swarm mode must be enabled for these endpoints to work.
paths:
  /services:
    get:
      summary: List services
      operationId: ServiceList
      responses:
        200:
          description: no error
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Service'
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Service'
        500:
          description: server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        503:
          description: node is not part of a swarm
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      parameters:
      - name: filters
        in: query
        description: 'A JSON encoded value of the filters (a `map[string][]string`) to process on the services list. Available filters:


          - `id=<service id>`

          - `label=<service label>`

          - `mode=["replicated"|"global"]`

          - `name=<service name>`

          '
        schema:
          type: string
      tags:
      - Service
  /services/create:
    post:
      summary: Create a service
      operationId: ServiceCreate
      responses:
        201:
          description: no error
          content:
            application/json:
              schema:
                type: object
                properties:
                  ID:
                    description: The ID of the created service.
                    type: string
                  Warning:
                    description: Optional warning message
                    type: string
                example:
                  ID: ak7w3gjqoa3kuz8xcpnyy0pvl
                  Warning: 'unable to pin image doesnotexist:latest to digest: image library/doesnotexist:latest not found'
        400:
          description: bad parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        403:
          description: network is not eligible for services
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        409:
          description: name conflicts with an existing service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        503:
          description: node is not part of a swarm
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      parameters:
      - name: X-Registry-Auth
        in: header
        description: A base64-encoded auth configuration for pulling from private registries. [See the authentication section for details.](#section/Authentication)
        schema:
          type: string
      tags:
      - Service
      requestBody:
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/ServiceSpec'
              - type: object
                example:
                  Name: web
                  TaskTemplate:
                    ContainerSpec:
                      Image: nginx:alpine
                      Mounts:
                      - ReadOnly: true
                        Source: web-data
                        Target: /usr/share/nginx/html
                        Type: volume
                        VolumeOptions:
                          DriverConfig: {}
                          Labels:
                            com.example.something: something-value
                      Hosts:
                      - 10.10.10.10 host1
                      - ABCD:EF01:2345:6789:ABCD:EF01:2345:6789 host2
                      User: '33'
                      DNSConfig:
                        Nameservers:
                        - 8.8.8.8
                        Search:
                        - example.org
                        Options:
                        - timeout:3
                      Secrets:
                      - File:
                          Name: www.example.org.key
                          UID: '33'
                          GID: '33'
                          Mode: 384
                        SecretID: fpjqlhnwb19zds35k8wn80lq9
                        SecretName: example_org_domain_key
                    LogDriver:
                      Name: json-file
                      Options:
                        max-file: '3'
                        max-size: 10M
                    Placement: {}
                    Resources:
                      Limits:
                        MemoryBytes: 104857600
                      Reservations: {}
                    RestartPolicy:
                      Condition: on-failure
                      Delay: 10000000000
                      MaxAttempts: 10
                  Mode:
                    Replicated:
                      Replicas: 4
                  UpdateConfig:
                    Parallelism: 2
                    Delay: 1000000000
                    FailureAction: pause
                    Monitor: 15000000000
                    MaxFailureRatio: 0.15
                  RollbackConfig:
                    Parallelism: 1
                    Delay: 1000000000
                    FailureAction: pause
                    Monitor: 15000000000
                    MaxFailureRatio: 0.15
                  EndpointSpec:
                    Ports:
                    - Protocol: tcp
                      PublishedPort: 8080
                      TargetPort: 80
                  Labels:
                    foo: bar
        required: true
  /services/{id}:
    get:
      summary: Inspect a service
      operationId: ServiceInspect
      responses:
        200:
          description: no error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
            text/plain:
              schema:
                $ref: '#/components/schemas/Service'
        404:
          description: no such service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        503:
          description: node is not part of a swarm
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      parameters:
      - name: id
        in: path
        description: ID or name of service.
        required: true
        schema:
          type: string
      - name: insertDefaults
        in: query
        description: Fill empty fields with default values.
        schema:
          type: boolean
          default: false
      tags:
      - Service
    delete:
      summary: Delete a service
      operationId: ServiceDelete
      responses:
        200:
          description: no error
        404:
          description: no such service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        503:
          description: node is not part of a swarm
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      parameters:
      - name: id
        in: path
        description: ID or name of service.
        required: true
        schema:
          type: string
      tags:
      - Service
  /services/{id}/update:
    post:
      summary: Update a service
      operationId: ServiceUpdate
      responses:
        200:
          description: no error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceUpdateResponse'
        400:
          description: bad parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: no such service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        503:
          description: node is not part of a swarm
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      parameters:
      - name: id
        in: path
        description: ID or name of service.
        required: true
        schema:
          type: string
      - name: version
        in: query
        description: The version number of the service object being updated. This is required to avoid conflicting writes.
        required: true
        schema:
          type: integer
      - name: registryAuthFrom
        in: query
        description: If the X-Registry-Auth header is not specified, this parameter indicates where to find registry authorization credentials. The valid values are `spec` and `previous-spec`.
        schema:
          type: string
          default: spec
      - name: rollback
        in: query
        description: Set to this parameter to `previous` to cause a server-side rollback to the previous service spec. The supplied spec will be ignored in this case.
        schema:
          type: string
      - name: X-Registry-Auth
        in: header
        description: A base64-encoded auth configuration for pulling from private registries. [See the authentication section for details.](#section/Authentication)
        schema:
          type: string
      tags:
      - Service
      requestBody:
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/ServiceSpec'
              - type: object
                example:
                  Name: top
                  TaskTemplate:
                    ContainerSpec:
                      Image: busybox
                      Args:
                      - top
                    Resources:
                      Limits: {}
                      Reservations: {}
                    RestartPolicy:
                      Condition: any
                      MaxAttempts: 0
                    Placement: {}
                    ForceUpdate: 0
                  Mode:
                    Replicated:
                      Replicas: 1
                  UpdateConfig:
                    Parallelism: 2
                    Delay: 1000000000
                    FailureAction: pause
                    Monitor: 15000000000
                    MaxFailureRatio: 0.15
                  RollbackConfig:
                    Parallelism: 1
                    Delay: 1000000000
                    FailureAction: pause
                    Monitor: 15000000000
                    MaxFailureRatio: 0.15
                  EndpointSpec:
                    Mode: vip
        required: true
  /services/{id}/logs:
    get:
      summary: Get service logs
      description: 'Get `stdout` and `stderr` logs from a service.


        **Note**: This endpoint works only for services with the `json-file` or `journald` logging drivers.'
      operationId: ServiceLogs
      responses:
        101:
          description: logs returned as a stream
          content:
            application/vnd.docker.raw-stream:
              schema:
                type: string
                format: binary
            application/json:
              schema:
                type: string
                format: binary
        200:
          description: logs returned as a string in response body
          content:
            application/vnd.docker.raw-stream:
              schema:
                type: string
            application/json:
              schema:
                type: string
        404:
          description: no such service
          content:
            application/vnd.docker.raw-stream:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: 'No such service: c2ada9df5af8'
        500:
          description: server error
          content:
            application/vnd.docker.raw-stream:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        503:
          description: node is not part of a swarm
          content:
            application/vnd.docker.raw-stream:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      parameters:
      - name: id
        in: path
        required: true
        description: ID or name of the service
        schema:
          type: string
      - name: details
        in: query
        description: Show service context and extra details provided to logs.
        schema:
          type: boolean
          default: false
      - name: follow
        in: query
        description: 'Return the logs as a stream.


          This will return a `101` HTTP response with a `Connection: upgrade` header, then hijack the HTTP connection to send raw output. For more information about hijacking and the stream format, [see the documentation for the attach endpoint](#operation/ContainerAttach).

          '
        schema:
          type: boolean
          default: false
      - name: stdout
        in: query
        description: Return logs from `stdout`
        schema:
          type: boolean
          default: false
      - name: stderr
        in: query
        description: Return logs from `stderr`
        schema:
          type: boolean
          default: false
      - name: since
        in: query
        description: Only return logs since this time, as a UNIX timestamp
        schema:
          type: integer
          default: 0
      - name: timestamps
        in: query
        description: Add timestamps to every log line
        schema:
          type: boolean
          default: false
      - name: tail
        in: query
        description: Only return this number of log lines from the end of the logs. Specify as an integer or `all` to output all log lines.
        schema:
          type: string
          default: all
      tags:
      - Service
components:
  schemas:
    ObjectVersion:
      description: 'The version number of the object such as node, service, etc. This is needed to avoid conflicting writes.

        The client must send the version number along with the modified specification when updating these objects.

        This approach ensures safe concurrency and determinism in that the change on the object

        may not be applied if the version number has changed from the last read. In other words,

        if two update requests specify the same base version, only one of the requests can succeed.

        As a result, two separate update requests that happen at the same time will not

        unintentionally overwrite each other.

        '
      type: object
      properties:
        Index:
          type: integer
          format: uint64
          example: 373531
    GenericResources:
      description: User-defined resources can be either Integer resources (e.g, `SSD=3`) or String resources (e.g, `GPU=UUID1`)
      type: array
      items:
        type: object
        properties:
          NamedResourceSpec:
            type: object
            properties:
              Kind:
                type: string
              Value:
                type: string
          DiscreteResourceSpec:
            type: object
            properties:
              Kind:
                type: string
              Value:
                type: integer
                format: int64
      example:
      - DiscreteResourceSpec:
          Kind: SSD
          Value: 3
      - NamedResourceSpec:
          Kind: GPU
          Value: UUID1
      - NamedResourceSpec:
          Kind: GPU
          Value: UUID2
    EndpointSpec:
      description: Properties that can be configured to access and load balance a service.
      type: object
      properties:
        Mode:
          description: The mode of resolution to use for internal load balancing between tasks.
          type: string
          enum:
          - vip
          - dnsrr
          default: vip
        Ports:
          description: List of exposed ports that this service is accessible on from the outside. Ports can only be provided if `vip` resolution mode is used.
          type: array
          items:
            $ref: '#/components/schemas/EndpointPortConfig'
    EndpointPortConfig:
      type: object
      properties:
        Name:
          type: string
        Protocol:
          type: string
          enum:
          - tcp
          - udp
        TargetPort:
          description: The port inside the container.
          type: integer
        PublishedPort:
          description: The port on the swarm hosts.
          type: integer
    TaskSpec:
      description: User modifiable task configuration.
      type: object
      properties:
        PluginSpec:
          type: object
          description: Invalid when specified with `ContainerSpec`. *(Experimental release only.)*
          properties:
            Name:
              description: The name or 'alias' to use for the plugin.
              type: string
            Remote:
              description: The plugin image reference to use.
              type: string
            Disabled:
              description: Disable the plugin once scheduled.
              type: boolean
            PluginPrivilege:
              type: array
              items:
                description: Describes a permission accepted by the user upon installing the plugin.
                type: object
                properties:
                  Name:
                    type: string
                  Description:
                    type: string
                  Value:
                    type: array
                    items:
                      type: string
        ContainerSpec:
          type: object
          description: Invalid when specified with `PluginSpec`.
          properties:
            Image:
              description: The image name to use for the container
              type: string
            Labels:
              description: User-defined key/value data.
              type: object
              additionalProperties:
                type: string
            Command:
              description: The command to be run in the image.
              type: array
              items:
                type: string
            Args:
              description: Arguments to the command.
              type: array
              items:
                type: string
            Hostname:
              description: The hostname to use for the container, as a valid RFC 1123 hostname.
              type: string
            Env:
              description: A list of environment variables in the form `VAR=value`.
              type: array
              items:
                type: string
            Dir:
              description: The working directory for commands to run in.
              type: string
            User:
              description: The user inside the container.
              type: string
            Groups:
              type: array
              description: A list of additional groups that the container process will run as.
              items:
                type: string
            Privileges:
              type: object
              description: Security options for the container
              properties:
                CredentialSpec:
                  type: object
                  description: CredentialSpec for managed service account (Windows only)
                  properties:
                    File:
                      type: string
                      description: 'Load credential spec from this file. The file is read by the daemon, and must be present in the

                        `CredentialSpecs` subdirectory in the docker data directory, which defaults to

                        `C:\ProgramData\Docker\` on Windows.


                        For example, specifying `spec.json` loads `C:\ProgramData\Docker\CredentialSpecs\spec.json`.


                        <p><br /></p>


                        > **Note**: `CredentialSpec.File` and `CredentialSpec.Registry` are mutually exclusive.

                        '
                    Registry:
                      type: string
                      description: 'Load credential spec from this value in the Windows registry. The specified registry value must be

                        located in:


                        `HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Virtualization\Containers\CredentialSpecs`


                        <p><br /></p>



                        > **Note**: `CredentialSpec.File` and `CredentialSpec.Registry` are mutually exclusive.

                        '
                SELinuxContext:
                  type: object
                  description: SELinux labels of the container
                  properties:
                    Disable:
                      type: boolean
                      description: Disable SELinux
                    User:
                      type: string
                      description: SELinux user label
                    Role:
                      type: string
                      description: SELinux role label
                    Type:
                      type: string
                      description: SELinux type label
                    Level:
                      type: string
                      description: SELinux level label
            TTY:
              description: Whether a pseudo-TTY should be allocated.
              type: boolean
            OpenStdin:
              description: Open `stdin`
              type: boolean
            ReadOnly:
              description: Mount the container's root filesystem as read only.
              type: boolean
            Mounts:
              description: Specification for mounts to be added to containers created as part of the service.
              type: array
              items:
                $ref: '#/components/schemas/Mount'
            StopSignal:
              description: Signal to stop the container.
              type: string
            StopGracePeriod:
              description: Amount of time to wait for the container to terminate before forcefully killing it.
              type: integer
              format: int64
            HealthCheck:
              $ref: '#/components/schemas/HealthConfig'
            Hosts:
              type: array
              description: "A list of hostname/IP mappings to add to the container's `hosts`\nfile. The format of extra hosts is specified in the\n[hosts(5)](http://man7.org/linux/man-pages/man5/hosts.5.html)\nman page:\n\n    IP_address canonical_hostname [aliases...]\n"
              items:
                type: string
            DNSConfig:
              description: Specification for DNS related configurations in resolver configuration file (`resolv.conf`).
              type: object
              properties:
                Nameservers:
                  description: The IP addresses of the name servers.
                  type: array
                  items:
                    type: string
                Search:
                  description: A search list for host-name lookup.
                  type: array
                  items:
                    type: string
                Options:
                  description: A list of internal resolver variables to be modified (e.g., `debug`, `ndots:3`, etc.).
                  type: array
                  items:
                    type: string
            Secrets:
              description: Secrets contains references to zero or more secrets that will be exposed to the service.
              type: array
              items:
                type: object
                properties:
                  File:
                    description: File represents a specific target that is backed by a file.
                    type: object
                    properties:
                      Name:
                        description: Name represents the final filename in the filesystem.
                        type: string
                      UID:
                        description: UID represents the file UID.
                        type: string
                      GID:
                        description: GID represents the file GID.
                        type: string
                      Mode:
                        description: Mode represents the FileMode of the file.
                        type: integer
                        format: uint32
                  SecretID:
                    description: SecretID represents the ID of the specific secret that we're referencing.
                    type: string
                  SecretName:
                    description: 'SecretName is the name of the secret that this references, but this is just provided for

                      lookup/display purposes. The secret in the reference will be identified by its ID.

                      '
                    type: string
            Configs:
              description: Configs contains references to zero or more configs that will be exposed to the service.
              type: array
              items:
                type: object
                properties:
                  File:
                    description: File represents a specific target that is backed by a file.
                    type: object
                    properties:
                      Name:
                        description: Name represents the final filename in the filesystem.
                        type: string
                      UID:
                        description: UID represents the file UID.
                        type: string
                      GID:
                        description: GID represents the file GID.
                        type: string
                      Mode:
                        description: Mode represents the FileMode of the file.
                        type: integer
                        format: uint32
                  ConfigID:
                    description: ConfigID represents the ID of the specific config that we're referencing.
                    type: string
                  ConfigName:
                    description: 'ConfigName is the name of the config that this references, but this is just provided for

                      lookup/display purposes. The config in the reference will be identified by its ID.

                      '
                    type: string
        Resources:
          description: Resource requirements which apply to each individual container created as part of the service.
          type: object
          properties:
            Limits:
              description: Define resources limits.
              $ref: '#/components/schemas/ResourceObject'
            Reservation:
              description: Define resources reservation.
              $ref: '#/components/schemas/ResourceObject'
        RestartPolicy:
          description: Specification for the restart policy which applies to containers created as part of this service.
          type: object
          properties:
            Condition:
              description: Condition for restart.
              type: string
              enum:
              - none
              - on-failure
              - any
            Delay:
              description: Delay between restart attempts.
              type: integer
              format: int64
            MaxAttempts:
              description: Maximum attempts to restart a given container before giving up (default value is 0, which is ignored).
              type: integer
              format: int64
              default: 0
            Window:
              description: Windows is the time window used to evaluate the restart policy (default value is 0, which is unbounded).
              type: integer
              format: int64
              default: 0
        Placement:
          type: object
          properties:
            Constraints:
              description: An array of constraints.
              type: array
              items:
                type: string
              example:
              - node.hostname!=node3.corp.example.com
              - node.role!=manager
              - node.labels.type==production
            Preferences:
              description: Preferences provide a way to make the scheduler aware of factors such as topology. They are provided in order from highest to lowest precedence.
              type: array
              items:
                type: object
                properties:
                  Spread:
                    type: object
                    properties:
                      SpreadDescriptor:
                        description: label descriptor, such as engine.labels.az
                        type: string
              example:
              - Spread:
                  SpreadDescriptor: node.labels.datacenter
              - Spread:
                  SpreadDescriptor: node.labels.rack
            Platforms:
              description: 'Platforms stores all the platforms that the service''s image can

                run on. This field is used in the platform filter for scheduling.

                If empty, then the platform filter is off, meaning there are no

                scheduling restrictions.

                '
              type: array
              items:
                $ref: '#/components/schemas/Platform'
        ForceUpdate:
          description: A counter that triggers an update even if no relevant parameters have been changed.
          type: integer
        Runtime:
          description: Runtime is the type of runtime specified for the task executor.
          type: string
        Networks:
          type: array
          items:
            type: object
            properties:
              Target:
                type: string
              Aliases:
                type: array
                items:
                  type: string
        LogDriver:
          description: Specifies the log driver to use for tasks created from this spec. If not present, the default one for the swarm will be used, finally falling back to the engine default if not specified.
          type: object
          properties:
            Name:
              type: string
            Options:
              type: object
              additionalProperties:
                type: string
    Mount:
      type: object
      properties:
        Target:
          description: Container path.
          type: string
        Source:
          description: Mount source (e.g. a volume name, a host path).
          type: string
        Type:
          description: 'The mount type. Available types:


            - `bind` Mounts a file or directory from the host into the container. Must exist prior to creating the container.

            - `volume` Creates a volume with the given name and options (or uses a pre-existing volume with the same name and options). These are **not** removed when the container is removed.

            - `tmpfs` Create a tmpfs with the given options. The mount source cannot be specified for tmpfs.

            '
          type: string
          enum:
          - bind
          - volume
          - tmpfs
        ReadOnly:
          description: Whether the mount should be read-only.
          type: boolean
        Consistency:
          description: 'The consistency requirement for the mount: `default`, `consistent`, `cached`, or `delegated`.'
          type: string
        BindOptions:
          description: Optional configuration for the `bind` type.
          type: object
          properties:
            Propagation:
              description: A propagation mode with the value `[r]private`, `[r]shared`, or `[r]slave`.
              enum:
              - private
              - rprivate
              - shared
              - rshared
              - slave
              - rslave
        VolumeOptions:
          description: Optional configuration for the `volume` type.
          type: object
          properties:
            NoCopy:
              description: Populate volume with data from the target.
              type: boolean
              default: false
            Labels:
              description: User-defined key/value metadata.
              type: object
              additionalProperties:
                type: string
            DriverConfig:
              description: Map of driver specific options
              type: object
              properties:
                Name:
                  description: Name of the driver to use to create the volume.
                  type: string
                Options:
                  description: key/value map of driver specific options.
                  type: object
                  additionalProperties:
                    type: string
        TmpfsOptions:
          description: Optional configuration for the `tmpfs` type.
          type: object
          properties:
            SizeBytes:
              description: The size for the tmpfs mount in bytes.
              type: integer
              format: int64
            Mode:
              description: The permission mode for the tmpfs mount in an integer.
              type: integer
    Service:
      type: object
      properties:
        ID:
          type: string
        Version:
          $ref: '#/components/schemas/ObjectVersion'
        CreatedAt:
          type: string
          format: dateTime
        UpdatedAt:
          type: string
          format: dateTime
        Spec:
          $ref: '#/components/schemas/ServiceSpec'
        Endpoint:
          type: object
          properties:
            Spec:
              $ref: '#/components/schemas/EndpointSpec'
            Ports:
              type: array
              items:
                $ref: '#/components/schemas/EndpointPortConfig'
            VirtualIPs:
              type: array
              items:
                type: object
                properties:
                  NetworkID:
                    type: string
                  Addr:
                    type: string
        UpdateStatus:
          description: The status of a service update.
          type: object
          properties:
            State:
              type: string
              enum:
              - updating
              - paused
              - completed
            StartedAt:
              type: string
              format: dateTime
            CompletedAt:
              type: string
              format: dateTime
            Message:
              type: string
      example:
        ID: 9mnpnzenvg8p8tdbtq4wvbkcz
        Version:
          Index: 19
        CreatedAt: '2016-06-07T21:05:51.880065305Z'
        UpdatedAt: '2016-06-07T21:07:29.962229872Z'
        Spec:
          Name: hopeful_cori
          TaskTemplate:
            ContainerSpec:
              Image: redis
            Resources:
              Limits: {}
              Reservations: {}
            RestartPolicy:
              Condition: any
              MaxAttempts: 0
            Placement: {}
            ForceUpdate: 0
          Mode:
            Replicated:
              Replicas: 1
          UpdateConfig:
            Parallelism: 1
            Delay: 1000000000
            FailureAction: pause
            Monitor: 15000000000
            MaxFailureRatio: 0.15
          RollbackConfig:
            Parallelism: 1
            Delay: 1000000000
            FailureAction: pause
            Monitor: 15000000000
            MaxFailureRatio: 0.15
          EndpointSpec:
            Mode: vip
            Ports:
            - Protocol: tcp
              TargetPort: 6379
              PublishedPort: 30001
        Endpoint:
          Spec:
            Mode: vip
            Ports:
            - Protocol: tcp
              TargetPort: 6379
              PublishedPort: 30001
          Ports:
          - Protocol: tcp
            TargetPort: 6379
            PublishedPort: 30001
          VirtualIPs:
          - NetworkID: 4qvuz4ko70xaltuqbt8956gd1
            Addr: 10.255.0.2/16
          - NetworkID: 4qvuz4ko70xaltuqbt8956gd1
            Addr: 10.255.0.3/16
    ErrorResponse:
      description: Represents an error.
      type: object
      required:
      - message
      properties:
        message:
          description: The error message.
          type: string
      example:
        message: Something went wrong.
    Platform:
      description: 'Platform represents the platform (Arch/OS).

        '
      type: object
      properties:
        Architecture:
          description: 'Architecture represents the hardware architecture (for example,

            `x86_64`).

            '
          type: string
          example: x86_64
        OS:
          description: 'OS represents the Operating System (for example, `linux` or `windows`).

            '
          type: string
          example: linux
    ServiceSpec:
      description: User modifiable configuration for a service.
      properties:
        Name:
          description: Name of the service.
          type: string
        Labels:
          description: User-defined key/value metadata.
          type: object
          additionalProperties:
            type: string
        TaskTemplate:
          $ref: '#/components/schemas/TaskSpec'
        Mode:
          description: Scheduling mode for the service.
          type: object
          properties:
            Replicated:
              type: object
              properties:
                Replicas:
                  type: integer
                  format: int64
            Global:
              type: object
        UpdateConfig:
          description: Specification for the update strategy of the service.
          type: object
          properties:
            Parallelism:
              description: Maximum number of tasks to be updated in one iteration (0 means unlimited parallelism).
              type: integer
              format: int64
            Delay:
              description: Amount of time between updates, in nanoseconds.
              type: integer
              format: int64
            FailureAction:
              description: Action to take if an updated task fails to run, or stops running during the update.
              type: string
              enum:
              - continue
              - pause
              - rollback
            Monitor:
              description: Amount of time to monitor each updated task for failures, in nanoseconds.
              type: integer
              format: int64
            MaxFailureRatio:
              description: The fraction of tasks that may fail during an update before the failure action is invoked, specified as a floating point number between 0 and 1.
              type: number
              default: 0
            Order:
              description: The order of operations when rolling out an updated task. Either the old task is shut down before the new task is started, or the new task is started before the old task is shut down.
              type: string
              enum:
              - stop-first
              - start-first
        RollbackConfig:
          description: Specification for the rollback strategy of the service.
          type: object
          properties:
            Parallelism:
              description: Maximum number of tasks to be rolled back in one iteration (0 means unlimited parallelism).
              type: integer
              format: int64
            Delay:
              description: Amount of time between rollback iterations, in nanoseconds.
              type: integer
              format: int64
            FailureAction:
              description: Action to take if an rolled back task fails to run, or stops running during the rollback.
              type: string
              enum:
              - continue
              - pause
            Monitor:
              description: Amount of time to monitor each rolled back task for failures, in nanoseconds.
              type: integer
              format: int64
            MaxFailureRatio:
              description: The fraction of tasks that may fail during a rollback before the failure action is invoked, specified as a floating point number between 0 and 1.
              type: number
              default: 0
            Order:
              description: The order of operations when rolling back a task. Either the old task is shut down before the new task is started, or the new task is started before the old task is shut down.
              type: string
              enum:
              - stop-first
              - start-first
        Networks:
          description: Array of network names or IDs to attach the service to.
          type: array
          items:
            type: object
            properties:
              Target:
                type: string
              Aliases:
                type: array
                items:
                  type: string
        EndpointSpec:
          $ref: '#/components/schemas/EndpointSpec'
    ResourceObject:
      description: An object describing the resources which can be advertised by a node and requested by a task
      type: object
      properties:
        NanoCPUs:
          type: integer
          format: int64
          example: 4000000000
        MemoryBytes:
          type: integer
          format: int64
          example: 8272408576
        GenericResources:
          $ref: '#/components/schemas/GenericResources'
    HealthConfig:
      description: A test to perform to check that the container is healthy.
      type: object
      properties:
        Test:
          description: 'The test to perform. Possible values are:


            - `[]` inherit healthcheck from image or parent image

            - `["NONE"]` disable healthcheck

            - `["CMD", args...]` exec arguments directly

            - `["CMD-SHELL", command]` run command with system''s default shell

            '
          type: array
          items:
            type: string
        Interval:
          description: The time to wait between checks in nanoseconds. It should be 0 or at least 1000000 (1 ms). 0 means inherit.
          type: integer
        Timeout:
          description: The time to wait before considering the check to have hung. It should be 0 or at least 1000000 (1 ms). 0 means inherit.
          type: integer
        Retries:
          description: The number of consecutive failures needed to consider a container as unhealthy. 0 means inherit.
          type: integer
        StartPeriod:
          description: Start period for the container to initialize before starting health-retries countdown in nanoseconds. It should be 0 or at least 1000000 (1 ms). 0 means inherit.
          type: integer
    ServiceUpdateResponse:
      type: object
      properties:
        Warnings:
          description: Optional warning messages
          type: array
          items:
            type: string
      example:
        Warning: 'unable to pin image doesnotexist:latest to digest: image library/doesnotexist:latest not found'
